Adding `--path` argument in `apistar validate`
Just copy-pasting the README instructions and got:

```bash
user@user: ~Documents/projects apistar validate
Error: Schema file "schema.yaml" not found.
```

I went into the code, and found that `apistar validate` actually looks for `schema.yml` instead of `schema.yaml`.